esphome:
  name: siebenuhr
  friendly_name: Siebenuhr
  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - file://<insert_your_path_to_siebenuhr_core_here>


esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [ siebenuhr ]
    refresh: 0s

logger:
  # level: ERROR

api:
  encryption:
    key: "<insert_your_key_here>"

ota:
  - platform: esphome
    password: "<insert_your_password_here>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s  # disables reboot on failed Wi-Fi

captive_portal:

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: siebenuhr
    id: my_siebenuhr
    name: Siebenuhr
    restore_mode: RESTORE_DEFAULT_ON 
    type: REGULAR
    auto_brightness: True
    color_wheel: True
    power_monitoring: True
    time_id: sntp_time

text:
  - platform: template
    mode: text
    id: siebenuhr_text_input
    name: "Siebenuhr Text Input"
    set_action:
      then:
        - lambda: |-
            esphome::siebenuhr::global_siebenuhr_clock->set_text(x);
