esphome:
  name: "siebenuhr"
  friendly_name: SiebenUhr::Mini

  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - https://github.com/soliddifference/siebenuhr_core.git
    # - file://C:\Users\yanni\projects\siebenuhr_core

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [ siebenuhr ]
    refresh: 0s

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: sntp_time

siebenuhr:
  id: my_clock
  type: 1 # 0=BIG 1=MINI
  time_id: sntp_time
  text: "hallo"