esphome:
  name: siebenuhr
  friendly_name: Siebenuhr
  platformio_options:
    build_flags:
      - -D FASTLED_DITHER_ENABLED=0
      - -D SENSOR_READ_INTERVAL_MS=5000
      # - -D DOUBLE_CLICK_PERSONALITY_ENABLED
  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - SPI
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit INA219
    - igorantolic/Ai Esp32 Rotary Encoder
    - siebenuhr_core=https://github.com/soliddifference/siebenuhr_core.git

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/soliddifference/siebenuhr_esphome.git
      ref: main
    components: [ siebenuhr ]
    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret apiKey

ota:
  - platform: esphome
    password: !secret otaPassword

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s # disables reboot on failed Wi-Fi
  # fast_connect: on # Uncomment if you want to use fast connect, required for hidden SSID

captive_portal:

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: siebenuhr
    id: my_siebenuhr
    name: Siebenuhr
    restore_mode: RESTORE_DEFAULT_ON 
    type: MINI # 28 LEDs per digit
    # type: REGULAR # 119 LEDs per digit (the big clock)
    personality: SOLIDCOLOR
    # personality: COLORWHEEL
    # personality: RAINBOW
    # personality: MOSAIK
    # auto_brightness: True
    power_monitoring: True
    time_id: sntp_time
    default_transition_length: 0s

text:
  - platform: template
    mode: text
    id: siebenuhr_text_input
    name: "Siebenuhr Text Input"
    set_action:
      then:
        - lambda: |-
            // esphome::siebenuhr::global_siebenuhr_clock->set_text(x);
            esphome::siebenuhr::global_siebenuhr_clock->set_notification(x, 4000);
