esphome:
  name: siebenuhr
  friendly_name: Siebenuhr
  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - file://<path_to_your_project>\siebenuhr_core

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [ siebenuhr ]
    refresh: 0s

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s  # disables reboot on failed Wi-Fi

captive_portal:

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: siebenuhr
    id: my_siebenuhr
    name: Siebenuhr::Mini
    type: 1 # 0=BIG 1=MINI

text:
  - platform: template
    mode: text
    id: siebenuhr_text_input
    name: "Siebenuhr Text Input"
    set_action:
      then:
        # - logger.log:
        #     format: "Received: %s"
        #     args: [x.c_str()]
        - lambda: |-
            esphome::siebenuhr::global_siebenuhr_clock->set_text(x);
