esphome:
  name: "siebenuhr"
  friendly_name: SiebenUhr::Mini

  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - SPI
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit INA219
    - igorantolic/Ai Esp32 Rotary Encoder
    - https://github.com/soliddifference/siebenuhr_core.git

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: git
      url: https://github.com/soliddifference/siebenuhr_esphome.git
      ref: main
    components: [ siebenuhr ]
    refresh: 0s

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: siebenuhr
    id: my_siebenuhr
    name: Siebenuhr
    restore_mode: RESTORE_DEFAULT_ON 
    type: REGULAR
    personality: SOLIDCOLOR
    # auto_brightness: True
    power_monitoring: True
    time_id: sntp_time
    default_transition_length: 0s


text:
  - platform: template
    mode: text
    id: siebenuhr_text_input
    name: "Siebenuhr Text Input"
    set_action:
      then:
        # - logger.log:
        #     format: "Received: %s"
        #     args: [x.c_str()]
        - lambda: |-
            // esphome::siebenuhr::global_siebenuhr_clock->set_color(CRBG(255,0,0));
            esphome::siebenuhr::global_siebenuhr_clock->set_text(x);
