esphome:
  name: siebenuhr
  friendly_name: Siebenuhr
  libraries:
    - Fastled
    - RunningAverage
    - Wire
    - BH1750
    - SPI
    - adafruit/Adafruit BusIO
    - adafruit/Adafruit INA219
    - igorantolic/Ai Esp32 Rotary Encoder
    - file://<insert_your_path_to_siebenuhr_core_here>


esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [ siebenuhr ]
    refresh: 0s

logger:
  # level: ERROR

api:
  encryption:
    key: !secret apiKey
    #key: "<insert_your_key_here>"

ota:
  - platform: esphome
    password: !secret otaPassword
    # password: "<insert_your_password_here>"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s  # disables reboot on failed Wi-Fi
  # fast_connect: on # Uncomment if you want to use fast connect, required for hidden SSID

captive_portal:

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: siebenuhr
    id: my_siebenuhr
    name: Siebenuhr
    restore_mode: RESTORE_DEFAULT_ON 
    type: REGULAR # alternate value: MINI
    personality: COLORWHEEL
    # personality: SOLIDCOLOR
    # personality: RAINBOW
    # personality: MOSAIK
    # auto_brightness: True
    power_monitoring: True
    time_id: sntp_time
    default_transition_length: 0s

text:
  - platform: template
    mode: text
    id: siebenuhr_text_input
    name: "Siebenuhr Text Input"
    set_action:
      then:
        - lambda: |-
            // esphome::siebenuhr::global_siebenuhr_clock->set_text(x);
            esphome::siebenuhr::global_siebenuhr_clock->set_notification(x, 4000);
