esphome:
  name: "siebenuhr"
  friendly_name: SiebenUhr::Mini

  libraries:
    - https://github.com/soliddifference/siebenuhr_core.git

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: ./components
    components: [ siebenuhr ]
    refresh: 0s

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: sntp
    id: sntp_time

siebenuhr:
  id: my_clock
  mode: 1
  time_id: sntp_time
  text: "hallo"